##  Step 1: Import Libraries

In [16]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

## Step 2: Import Dataset

In [2]:
claimants_data=pd.read_csv("Claimants.csv")
claimants_data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

## Step 3: Data Analysis

In [3]:
claimants_data.shape

(1340, 7)

In [4]:
claimants_data.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [5]:
claimants_data.describe()

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
count,1340.000000,1340.000000,1328.000000,1299.000000,1292.000000,1151.000000,1340.000000
mean,11202.001493,0.488806,0.558735,0.907621,0.017028,28.414422,3.806307
std,9512.750796,0.500061,0.496725,0.289671,0.129425,20.304451,10.636903
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4177.000000,0.000000,0.000000,1.000000,0.000000,9.000000,0.400000
50%,8756.500000,0.000000,1.000000,1.000000,0.000000,30.000000,1.069500
75%,15702.500000,1.000000,1.000000,1.000000,0.000000,43.000000,3.781500
max,34153.000000,1.000000,1.000000,1.000000,1.000000,95.000000,173.604000

In [6]:
claimants_data.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

## Step 4: Data Preparation

#### 4.1 Data Cleaning

In [7]:
claimants_data=claimants_data.dropna()

In [8]:
claimants_data.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [9]:
claimants_data.shape

(1096, 7)

#### 4.2 Separate your inputs and output

In [15]:
X=claimants_data.drop(labels=["CASENUM","ATTORNEY"],axis=1)
X
#Dropping CASENUM, as it's not gonna make any sense in prediction and ATTORNEY is output

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1334     1.0       1.0       0.0    16.0   0.060
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1096 rows x 5 columns]

In [13]:
y=claimants_data["ATTORNEY"]

## Step 5: Model Building

In [17]:
claimants_model=LogisticRegression()

## Step 6: Model Training

In [18]:
claimants_model.fit(X,y)

LogisticRegression()

## Step 7: Model Testing

In [25]:
y_pred=claimants_model.predict(X)
claimants_data["Predicted Output"]=y_pred
claimants_data["Predicted Output"]

C:\Users\User\AppData\Local\Temp\ipykernel_10032\238997158.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  claimants_data["Predicted Output"]=y_pred

0       0
1       1
2       1
3       0
4       1
       ..
1334    1
1336    0
1337    1
1338    0
1339    1
Name: Predicted Output, Length: 1096, dtype: int64

## Step 8: Model Evaluation

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true=y,y_pred=y_pred)

0.708029197080292

## Step 9: Model Deployment

In [29]:
from pickle import dump
dump(claimants_model,open("claimants.pkl","wb"))