## Step 1: Import Libraries

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

## Step 2: Import Dataset

In [2]:
cars_data=pd.read_csv("Cars.csv")
cars_data.head()

   HP        MPG  VOL          SP         WT
0  49  53.700681   89  104.185353  28.762059
1  55  50.013401   92  105.461264  30.466833
2  55  50.013401   92  105.461264  30.193597
3  70  45.696322   92  113.461264  30.632114
4  53  50.504232   92  104.461264  29.889149

## Step 3: Data Understanding

In [3]:
cars_data.dtypes

HP       int64
MPG    float64
VOL      int64
SP     float64
WT     float64
dtype: object

In [4]:
cars_data.describe()

               HP        MPG         VOL          SP         WT
count   81.000000  81.000000   81.000000   81.000000  81.000000
mean   117.469136  34.422076   98.765432  121.540272  32.412577
std     57.113502   9.131445   22.301497   14.181432   7.492813
min     49.000000  12.101263   50.000000   99.564907  15.712859
25%     84.000000  27.856252   89.000000  113.829145  29.591768
50%    100.000000  35.152727  101.000000  118.208698  32.734518
75%    140.000000  39.531633  113.000000  126.404312  37.392524
max    322.000000  53.700681  160.000000  169.598513  52.997752

In [5]:
cars_data.isna().sum()

HP     0
MPG    0
VOL    0
SP     0
WT     0
dtype: int64

In [6]:
cars_data.shape

(81, 5)

## Step 4: Data Preparation

In [7]:
X=cars_data[["HP","SP","WT","VOL"]]
X

     HP          SP         WT  VOL
0    49  104.185353  28.762059   89
1    55  105.461264  30.466833   92
2    55  105.461264  30.193597   92
3    70  113.461264  30.632114   92
4    53  104.461264  29.889149   92
..  ...         ...        ...  ...
76  322  169.598513  16.132947   50
77  238  150.576579  37.923113  115
78  263  151.598513  15.769625   50
79  295  167.944460  39.423099  119
80  236  139.840817  34.948615  107

[81 rows x 4 columns]

In [8]:
y=cars_data["MPG"]

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,shuffle=True,random_state=41)

In [10]:
X_train

     HP          SP         WT  VOL
47   98  116.472936  33.910056  103
80  236  139.840817  34.948615  107
7    62  102.598513  15.847758   50
29  103  121.840817  35.549360  107
11   92  117.598513  15.753535   50
..  ...         ...        ...  ...
23   81  113.829145  31.837122   96
65  165  126.598513  15.712859   50
12   92  122.105055  32.813592   99
35   90  115.013085  31.911223   98
64  150  128.128401  40.159482  121

[64 rows x 4 columns]

In [11]:
X_test

     HP          SP         WT  VOL
73  140  124.715241  52.997752  160
24   95  119.185353  28.781728   89
77  238  150.576579  37.923113  115
54  160  135.392639  37.254392  113
32  102  119.921115  31.380041   97
6    55  105.461264  30.308480   92
42  102  117.461264  30.527427   92
76  322  169.598513  16.132947   50
43   95  114.093383  28.343976   88
0    49  104.185353  28.762059   89
2    55  105.461264  30.193597   92
67  165  133.680223  41.573975  127
45  100  117.105055  32.621916   99
37  102  116.909442  27.879915   86
38  102  116.909442  28.630502   86
27   92  119.105055  32.835069   99
48  130  127.909442  28.070597   86

In [12]:
y_train

47    35.052330
80    12.101263
7     46.716554
29    35.404192
11    39.354094
        ...
23    40.474723
65    40.050000
12    39.354094
35    37.958743
64    23.605158
Name: MPG, Length: 64, dtype: float64

In [13]:
y_test

73    19.086341
24    38.310606
77    19.197888
54    26.852279
32    36.285456
6     50.013401
42    34.070668
76    36.900000
43    35.152727
0     53.700681
2     50.013401
67    23.103172
45    34.561499
37    34.070668
38    34.070668
27    38.411003
48    31.014131
Name: MPG, dtype: float64

## Step 5: Model Building

In [14]:
cars_model=LinearRegression()

## Step 6: Model Training

In [15]:
cars_model.fit(X_train,y_train)

LinearRegression()

## Step 7: Model Testing

Testing Training data

In [16]:
y_pred_train=cars_model.predict(X_train)
y_pred_train

array([35.63538566, 13.484901  , 46.92249208, 36.31689685, 46.79521163,
       41.33079437, 25.34414449, 45.51032047, 20.70785704, 24.20592991,
       41.45176143, 41.6147366 , 19.12345179, 34.56739571, 34.52271511,
       35.28696046, 41.0365751 , 41.78760373, 32.93950259, 23.75033756,
       41.54061385, 47.0797592 , 35.50440428, 37.81778982, 32.55579178,
       35.4030443 , 39.01650997, 29.68627631, 38.26014548, 35.86294415,
       35.60518182, 26.42579818, 38.86644821, 43.22353765, 32.71701209,
       23.19082352, 22.68054515, 25.57940132, 22.65433819, 42.59952696,
       42.42854375, 37.39802664, 37.3229286 , 34.92374097, 41.54525292,
       38.28861137, 27.2604251 , 38.47239724, 46.93061593, 28.92756818,
       29.60501218, 32.93281505, 28.64949755, 24.67590203, 32.86435571,
       10.6692653 , 42.830145  , 35.26851416, 36.35123034, 39.69477294,
       33.94932455, 40.39061904, 37.60974687, 25.77936704])

Testing test data

In [17]:
y_pred_test=cars_model.predict(X_test)
y_pred_test

array([19.57120554, 39.91585919, 16.6125558 , 28.12933599, 37.18690868,
       42.55086066, 37.19747207, 17.30599063, 37.72919002, 43.7243243 ,
       42.515554  , 23.59375821, 36.18377576, 37.81005808, 38.04073383,
       39.02331403, 36.4029859 ])

## Step 8: Model Evaluation

Training data error

In [18]:
training_error=y_train-y_pred_train
training_error

47   -0.583056
80   -1.383638
7    -0.205938
29   -0.912704
11   -7.441118
        ...
23    0.779950
65    6.100675
12   -1.036525
35    0.348996
64   -2.174209
Name: MPG, Length: 64, dtype: float64

In [19]:
mean_absolute_error(y_train,y_pred_train)

2.849002367711459

Teesting data error

In [20]:
testing_error=y_test-y_pred_test
testing_error

73    -0.484865
24    -1.605253
77     2.585332
54    -1.277057
32    -0.901452
6      7.462540
42    -3.126804
76    19.594009
43    -2.576463
0      9.976357
2      7.497847
67    -0.490587
45    -1.622277
37    -3.739390
38    -3.970066
27    -0.612311
48    -5.388855
Name: MPG, dtype: float64

In [21]:
mean_absolute_error(y_test,y_pred_test)

4.288909693428923